apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus
spec:
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
      - name: eventbus
        image: docker.io/library/rabbitmq:3.13
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672  # AMQP protocol
        env: 
        - name: RABBITMQ_DEFAULT_PASS
          value: YJr23N850SJBBqn9UUrXnE
        - name: RABBITMQ_DEFAULT_USER
          value: eshop
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus
spec:
  selector:
    app: eventbus
  ports:
  - port: 5672
    targetPort: 5672
    name: protocol
