apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api
        image: dahalsujata52897/ordering-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: ConnectionStrings__eventbus
          value: amqp://eshop:YJr23N850SJBBqn9UUrXnE@eventbus:5672
        - name: ConnectionStrings__orderingdb
          value: Host=db;Port=5432;Username=postgres;Password=Testtest#111;Database=orderingdb
        - name: DOTNET_LAUNCH_PROFILE
          value: http
        - name: DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION
          value: "true" 
        - name: Identity__Url
          value: https://eshop.local
        # - name: ConnectionStrings__eventbus
        #   valueFrom:
        #     configMapKeyRef:
        #       name: all-env
        #       key: ConnectionStrings__eventbus
        # - name: ConnectionStrings__orderingdb
        #   valueFrom:
        #     configMapKeyRef:
        #       name: all-env
        #       key: ConnectionStrings__orderingdb
        # - name: Identity__Url
        #   valueFrom:
        #     configMapKeyRef:
        #       name: all-env
        #       key: identity_url
        # - name: HTTP_PORTS
        #   valueFrom:
        #     configMapKeyRef:
        #       name: all-env
        #       key: HTTP_PORTS
        # - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        #   valueFrom:
        #     configMapKeyRef:
        #       name: all-env
        #       key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        # - name: ASPNETCORE_ENVIRONMENT
        #   value: Development
        volumeMounts:
        - mountPath: /home/app/.aspnet/DataProtection-Keys
          name: data
      volumes:
      - name: data
        persistentVolumeClaim: 
          claimName: pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ordering-api
spec:
  selector:
    app: ordering-api
  ports:
  - port: 8080
    targetPort: 8080
