apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-api
spec:
  selector:
    matchLabels:
      app: webhooks-api
  template:
    metadata:
      labels:
        app: webhooks-api
    spec:
      containers:
      - name: webhooks-api
        image: dahalsujata52897/webhooks-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: Identity__Url
          value: https://eshop.local
        - name: ConnectionStrings__webhooksdb
          value: Host=db;Port=5432;Username=postgres;Password=Testtest#111;Database=webhooksdb       
        - name: ConnectionStrings__eventbus
          value: amqp://eshop:YJr23N850SJBBqn9UUrXnE@eventbus:5672
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DOTNET_LAUNCH_PROFILE 
          value: http
        volumeMounts:
        - mountPath: /home/app/.aspnet/DataProtection-Keys
          name: data
      volumes:
      - name: data
        persistentVolumeClaim: 
          claimName: pvc
---
apiVersion: v1
kind: Service
metadata:
  name: webhooks-api
spec:
  selector:
    app: webhooks-api
  ports:
  - port: 8080
    targetPort: 8080